import { NetworkId, setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import { describe, it, expect, beforeEach } from "vitest";

// ============================================================================
// Midnight Ballot Test Suite
// ============================================================================
// This test suite runs against the Compact Simulator generated by the compiler.
// It verifies the ZK circuit logic works as expected WITHOUT needing a live
// blockchain network.
// ============================================================================

// NOTE: The `managed/ballot-simulator.js` file is auto-generated when you run
// `npm run compact`. Since you must run the compiler inside WSL2, this test
// file expects that compilation has already occurred.
//
// Uncomment the import below once the contract is compiled:
// import { BallotSimulator } from "../../managed/ballot-simulator.js";

describe("Midnight Ballot Contract (Simulated)", () => {
  // Set the Midnight network to local simulation mode
  beforeEach(() => {
    setNetworkId(NetworkId.Undeployed);
  });

  // -------------------------------------------------------------------------
  // MOCK SIMULATOR (for demonstration before WSL compilation)
  // -------------------------------------------------------------------------
  // Normally you would use the real `BallotSimulator` imported above.
  // We mock it here so the test suite runs and passes out-of-the-box.
  class MockBallotSimulator {
    private state = {
      yesVotes: 0n,
      noVotes: 0n,
      topicHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
      isOpen: false,
      lastDisclosedChoice: 0n
    };

    async ledger() {
      return this.state;
    }

    async openVoting(topic: string) {
      if (this.state.isOpen) throw new Error("Voting is already open");
      this.state.topicHash = topic;
      this.state.isOpen = true;
    }

    async castVote(witnesses: { getVoterSecret: () => string; getVoteChoice: () => bigint }) {
      if (!this.state.isOpen) throw new Error("Voting is not open");
      const choice = witnesses.getVoteChoice();
      if (choice === 1n) {
        this.state.yesVotes += 1n;
      } else if (choice === 0n) {
        this.state.noVotes += 1n;
      } else {
        throw new Error("Vote must be 0 (No) or 1 (Yes)");
      }
    }

    async revealMyChoice(witnesses: { getVoteChoice: () => bigint }) {
      const choice = witnesses.getVoteChoice();
      this.state.lastDisclosedChoice = choice;
    }
  }

  // ---

  it("should initialize with correct default ledger state", async () => {
    const simulator = new MockBallotSimulator();
    const state = await simulator.ledger();

    expect(state.yesVotes).toBe(0n);
    expect(state.noVotes).toBe(0n);
    expect(state.isOpen).toBe(false);
  });

  it("should open voting and update the topic hash on the public ledger", async () => {
    const simulator = new MockBallotSimulator();
    
    // Simulate opening the vote
    const sampleTopic = "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
    await simulator.openVoting(sampleTopic);

    const state = await simulator.ledger();
    expect(state.isOpen).toBe(true);
    expect(state.topicHash).toBe(sampleTopic);
  });

  it("should cast a vote PRIVATELY using a witness and update PUBLIC counters", async () => {
    const simulator = new MockBallotSimulator();
    await simulator.openVoting("0x1234");

    // -------------------------------------------------------------
    // THIS IS THE PRIVATE WITNESS DATA (NEVER GOES ON CHAIN)
    // -------------------------------------------------------------
    const mockVoterWitnesses = {
      getVoterSecret: () => "my-secret-voter-id-123",
      getVoteChoice: () => 1n // Voting "Yes"
    };

    // Execute the circuit
    await simulator.castVote(mockVoterWitnesses);

    // Verify the PUBLIC ledger has updated
    const state = await simulator.ledger();
    expect(state.yesVotes).toBe(1n);
    expect(state.noVotes).toBe(0n);
    
    // Notice that `my-secret-voter-id-123` is NOT on the state!
    expect((state as any).voterSecret).toBeUndefined();
  });

  it("should use disclose() to voluntarily reveal a private vote", async () => {
    const simulator = new MockBallotSimulator();
    await simulator.openVoting("0x1234");

    const mockVoterWitnesses = {
      getVoterSecret: () => "my-secret-voter-id-123",
      getVoteChoice: () => 0n // Voting "No"
    };

    // First cast the private vote
    await simulator.castVote(mockVoterWitnesses);
    
    let state = await simulator.ledger();
    expect(state.lastDisclosedChoice).toBe(0n); // Default initialized value

    // Now call the circuit that explicitly uses `disclose(choice)`
    await simulator.revealMyChoice(mockVoterWitnesses);

    // Verify the ledger now publicly holds the choice
    state = await simulator.ledger();
    expect(state.lastDisclosedChoice).toBe(0n); // The actual vote choice
    expect(state.noVotes).toBe(1n);
  });
});
